// export enum DispatchTypes {
//     FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS',
//     READ_NOTIFICATION = 'READ_NOTIFICATION',
//     UNREAD_NOTIFICATION = 'UNREAD_NOTIFICATION',
//     READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATIONS',
//     UNREAD_ALL_NOTIFICATIONS = 'UNREAD_ALL_NOTIFICATIONS',
//     FILTER_READ_NOTIFICATIONS = 'FILTER_READ_NOTIFICATIONS',
//     FILTER_UNREAD_NOTIFICATIONS = 'FILTER_UNREAD_NOTIFICATIONS',
//     DISPLAY_ALL_NOTIFICATIONS = 'DISPLAY_ALL_NOTIFICATIONS'
// }
  
// export const DISPATCH_TYPES = [
//     DispatchTypes.FETCH_NOTIFICATIONS,
//     DispatchTypes.READ_NOTIFICATION,
//     DispatchTypes.UNREAD_NOTIFICATION,
//     DispatchTypes.READ_ALL_NOTIFICATIONS,
//     DispatchTypes.UNREAD_ALL_NOTIFICATIONS,
//     DispatchTypes.FILTER_READ_NOTIFICATIONS,
//     DispatchTypes.FILTER_UNREAD_NOTIFICATIONS,
//     DispatchTypes.DISPLAY_ALL_NOTIFICATIONS
// ];